### ISSUE TITLE
Why does killing a channel also kill the connection?

### ISSUE THREAD

**Issue by tcoopman** [rabbitmq/rabbitmq-erlang-client#110]
I've first created this issue on the elixir client for amqp (https://github.com/pma/amqp/issues/112) but seeing it uses the erlang client underneed, I guess this is a better place for my question.

I'm going to repeat the issue here with the elixir syntax:

```elixir
iex(27)> {:ok, conn} = AMQP.Connection.open(username: conf.username, password: conf.password, host: conf.host)
iex(28)> {:ok, chan1} = AMQP.Channel.open(conn)
iex(29)> {:ok, chan2} = AMQP.Channel.open(conn)
iex(30)> Process.exit(chan1, :kill)
iex(31)> Process.alive?(conn.pid)
false
iex(32)> Process.alive?(chan2.pid)
false
```

I'm surprised that killing a channel also kills the connection. If I'm correct it's perfectly ok to have multiple channels over the same connection, so in the above example I would expect the connection and channel2 to still be alive.

The other way around is of course fine, if the connection dies, all related channels should die.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
Closing a channel does not affect the connection and neither does a channel level protocol exception. When channel number 0 (not exposed to applications) exits, that's considered to be unrecoverable for its connection.

It's a good question what should happen when a channel process is killed outright. I don't see anything in the code that would obviously close connection process termination plus you are using an Elixir wrapper. This needs more digging and thus belongs to the mailing list.

**Comment by michaelklishin** [comment]
Closing a channel does not affect the connection and neither does a channel level protocol exception. When channel number 0 (not exposed to applications) exits, that's considered to be unrecoverable for its connection.

It's a good question what should happen when a channel process is killed outright. I don't see anything in the code that would obviously close connection process termination plus you are using an Elixir wrapper. This needs more digging and thus belongs to the mailing list.

**Comment by tcoopman** [comment]
Thanks. For completeness, I've posted this on rabbitmq-users: https://groups.google.com/forum/#!topic/rabbitmq-users/nztNPoft4Es

I've also validated that without the Elixir wrapper killing a channel also kills the connection.
