### ISSUE TITLE
Please push 3.7.10 to hex.pm.

### ISSUE THREAD

**Issue by getong** [rabbitmq/rabbitmq-erlang-client#113]

**Comment by michaelklishin** [comment]
We won't be able to push 3.7.10. Due to a couple of Hex client changes and https://github.com/tsloughter/rebar3_hex/issues/87 the operation failed during the 3.7.10 GA release pipeline run. For reasons that are not very interesting we cannot retry this operation without rerunning all previous steps (100+ of them), which would mean effectively rebuilding the whole thing.

Hopefully 3.7.11 will be OK.

**Comment by michaelklishin** [comment]
[`3.7.11`](https://hex.pm/packages/amqp_client/3.7.11) is out.

**Comment by getong** [comment]
Yes, I found it on the hex.pm, thanks.
