### ISSUE TITLE
 rabbitmq-erlang-client/deps/rabbit/scripts/rabbitmq-plugins: No such file or directory

### ISSUE THREAD

**Issue by qiannianshaonian** [rabbitmq/rabbitmq-erlang-client#121]
gmake 
then gmake run-broker
but points
 rabbitmq-erlang-client/deps/rabbit/scripts/rabbitmq-plugins: No such file or directory

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
`gmake run-broker` makes no sense for this repository. If you want to start a REPL (shell), use `gmake shell`.

**Comment by qiannianshaonian** [comment]
thank you
