### ISSUE TITLE
Cannot connect to Broker

### ISSUE THREAD

**Issue by sammyraul** [rabbitmq/rabbitmq-erlang-client#81]
Hello,

I am unable to connect to RabbitMQ server using the erlang client. here's what I have done.

-module(producer).

-include("deps/amqp_client/include/amqp_client.hrl").

-export([produce/0]).

produce() ->
	io:format("Trying to connect"),
	{ok, Connection} = amqp_connection:start(#amqp_params_network{host="127.0.0.1"}).

Server is running on localhost (netstat output)

tcp        0      0 0.0.0.0:15672           0.0.0.0:*               LISTEN      17887/beam.smp  
tcp        0      0 127.0.0.1:5672          0.0.0.0:*               LISTEN      17887/beam.smp  
tcp        0      0 0.0.0.0:25672           0.0.0.0:*               LISTEN      17887/beam.smp  

I am facing the following error when I run producer:produce()

Trying to connect** exception exit: {noproc,{gen_server,call,
                                       [amqp_sup,
                                        {start_child,[{amqp_params_network,<<"guest">>,<<"guest">>,
                                                                           <<"/">>,"127.0.0.1",5672,0,0,10,infinity,none,
                                                                           [#Fun<amqp_auth_mechanisms.plain.3>,
                                                                            #Fun<amqp_auth_mechanisms.amqplain.3>],
                                                                           [],[]}]},
                                        infinity]}}
     in function  gen_server:call/3 (gen_server.erl, line 212)
     in call from amqp_connection:start/2 (src/amqp_connection.erl, line 174)
     in call from producer:produce/0 (src/producer.erl, line 9)

Any idea why?

Thanks
Sammy

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions of potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing, or at least sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by michaelklishin** [comment]
[Mailing list thread](https://groups.google.com/forum/#!topic/rabbitmq-users/P9AF6QKidfc).
